name: dotnet package

on: [push]

env:
  PROJECT_FOLDER: <projectfolder>
  TEST_PROJECT: <testprojectfolder>.csproj
  PROJECT: <project>.csproj
  NUGET_REPO_URL: https://nuget.pkg.github.com/jesus-uoc/index.json


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x

      - name: Install Dependencies
        run: dotnet restore $PROJECT_FOLDER/$PROJECT

      - name: Build Project
        run: dotnet build $PROJECT_FOLDER/$PROJECT

      - name: Install Test Project Dependencies
        run: dotnet restore $TEST_PROJECT

      - name: Test with dotnet
        run: dotnet test $TEST_PROJECT

      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT_FOLDER/$PROJECT

      - name: Publish the package to Rository
        run: dotnet nuget push $PROJECT_FOLDER/bin/Release/*.nupkg -k ${{ secrets.G_TOKEN }} -s $NUGET_REPO_URL
